## Server Config
server:
  port: 8080

##Spring Config
spring:

  ## DB Connection
  datasource:
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    username: ${DB_USERNAME}

  ## RabbitMQ Config
  rabbitmq:
    host: ${RABBIT_HOST}
    port: ${RABBIT_PORT}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
    virtual-host: ${RABBIT_VIRTUAL_HOST}
    dynamic: false

## JWT Config
jwt:
  secret: ${JWT_SECRET_KEY}
  get:
    token:
      uri: /authenticate

## Queue Config
rabbitmq:
  exchange:
    request: request-exchange
    response: response-exchange
  queue:
    plan-processing: plan-processing-queue
    plan-response: plan-response-queue
    billing-processing: billing-processing-queue
    billing-response: billing-response-queue
  routing-key:
    plan-processing: plan.processing
    plan-response: plan.response
    billing-processing: billing.processing
    billing-response: billing.response